backend:
  name: git-gateway
  branch: main

media_folder: "./"           # dónde sube archivos en el repo (raíz del sitio)
publish_mode: editorial_workflow

collections:
  - name: "carta"
    label: "Menú del Bar"
    files:
      - file: "_data/platos.json"
        label: "Editar Platos"
        name: "platos"
        fields:
          - { label: "Versión", name: "version", widget: "number", min: 1, default: 1 }
          - label: "Hamburguesas"
            name: "hamburguesas"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - label: "Título"
                name: "title"
                widget: "object"
                fields:
                  - {label: "ES", name: "es", widget: "string"}
                  - {label: "EU", name: "eu", widget: "string", required: false}
              - label: "Descripción"
                name: "desc"
                widget: "object"
                fields:
                  - {label: "ES", name: "es", widget: "text"}
                  - {label: "EU", name: "eu", widget: "text", required: false}
              - { label: "Precio", name: "price", widget: "string" }
              - { label: "Imagen (opcional)", name: "image", widget: "string", required: false }
              - { label: "Picante (0-2)", name: "spicy", widget: "number", min: 0, max: 2, default: 0 }
          - label: "Chuletas"
            name: "chuletas"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Título", name: "title", widget: "object", fields: [{label: "ES", name: "es", widget: "string"}, {label: "EU", name: "eu", widget: "string", required: false}] }
              - { label: "Descripción", name: "desc", widget: "object", fields: [{label: "ES", name: "es", widget: "text"}, {label: "EU", name: "eu", widget: "text", required: false}] }
              - { label: "Precio", name: "price", widget: "string" }
              - { label: "Imagen (opcional)", name: "image", widget: "string", required: false }
              - { label: "Picante (0-2)", name: "spicy", widget: "number", min: 0, max: 2, default: 0 }
          - label: "Raciones"
            name: "raciones"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Título", name: "title", widget: "object", fields: [{label: "ES", name: "es", widget: "string"}, {label: "EU", name: "eu", widget: "string", required: false}] }
              - { label: "Descripción", name: "desc", widget: "object", fields: [{label: "ES", name: "es", widget: "text"}, {label: "EU", name: "eu", widget: "text", required: false}] }
              - { label: "Precio", name: "price", widget: "string" }
              - { label: "Imagen (opcional)", name: "image", widget: "string", required: false }
              - { label: "Picante (0-2)", name: "spicy", widget: "number", min: 0, max: 2, default: 0 }
          - label: "Bocadillos"
            name: "bocadillos"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Título", name: "title", widget: "object", fields: [{label: "ES", name: "es", widget: "string"}, {label: "EU", name: "eu", widget: "string", required: false}] }
              - { label: "Descripción", name: "desc", widget: "object", fields: [{label: "ES", name: "es", widget: "text"}, {label: "EU", name: "eu", widget: "text", required: false}] }
              - { label: "Precio", name: "price", widget: "string" }
              - { label: "Imagen (opcional)", name: "image", widget: "string", required: false }
              - { label: "Picante (0-2)", name: "spicy", widget: "number", min: 0, max: 2, default: 0 }
          - label: "Postres"
            name: "postres"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Título", name: "title", widget: "object", fields: [{label: "ES", name: "es", widget: "string"}, {label: "EU", name: "eu", widget: "string", required: false}] }
              - { label: "Descripción", name: "desc", widget: "object", fields: [{label: "ES", name: "es", widget: "text"}, {label: "EU", name: "eu", widget: "text", required: false}] }
              - { label: "Precio", name: "price", widget: "string" }
              - { label: "Imagen (opcional)", name: "image", widget: "string", required: false }
              - { label: "Picante (0-2)", name: "spicy", widget: "number", min: 0, max: 2, default: 0 }
